### ISSUE TITLE
コンタクト用Google Formの作成

### ISSUE THREAD

**Issue by pddg** [StudioAquatan/web#5]
* 氏名 or ハンドルネーム
* 連絡先（メールアドレス）
* 問い合わせ内容の概要
  * 活動についての質問
  * 加入についての質問
  * その他
* 加入したいかどうか
  * 5段階評価くらい？

**Comment by taxio** [comment]
加入希望のフォームと問い合わせのフォームで分けるべきちゃう？

**Comment by pddg** [comment]
トップの`Join us`リンク開くと加入希望フォームに飛ぶようにするか．
